# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slimUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SlimAudioFileRefactor(object):
    def setupUi(self, SlimAudioFileRefactor):
        SlimAudioFileRefactor.setObjectName("SlimAudioFileRefactor")
        SlimAudioFileRefactor.resize(800, 561)
        SlimAudioFileRefactor.setMinimumSize(QtCore.QSize(800, 561))
        SlimAudioFileRefactor.setMaximumSize(QtCore.QSize(800, 561))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        SlimAudioFileRefactor.setFont(font)
        SlimAudioFileRefactor.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.centralwidget = QtWidgets.QWidget(SlimAudioFileRefactor)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 20, 741, 511))
        self.tabWidget.setMinimumSize(QtCore.QSize(741, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: white;\n"
"\n"
"")
        self.tabWidget.setIconSize(QtCore.QSize(25, 30))
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.widget.setFont(font)
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 30, 311, 31))
        self.label.setStyleSheet("font-weight: bold;\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(0, 0, 255);")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 80, 401, 41))
        self.lineEdit.setStyleSheet("border: 1px solid rgb(0, 0, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(430, 90, 41, 28))
        self.pushButton.setStyleSheet("\n"
"background-color: black;\n"
"color: white;\n"
"text-align: center;")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 200, 301, 31))
        self.label_2.setStyleSheet("font-weight: bold;\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(0, 0, 255);")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 250, 401, 41))
        self.lineEdit_2.setStyleSheet("border: 1px solid rgb(0, 0, 255);\n"
"border-radius: 30px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(430, 260, 41, 28))
        self.pushButton_2.setStyleSheet("\n"
"background-color: black;\n"
"color: white;\n"
"text-align: center;\n"
"border-radius: 50px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 380, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: white;\n"
"font: 87 10pt \"Arial Black\";\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.widget, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        SlimAudioFileRefactor.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SlimAudioFileRefactor)
        self.statusbar.setObjectName("statusbar")
        SlimAudioFileRefactor.setStatusBar(self.statusbar)

        self.retranslateUi(SlimAudioFileRefactor)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SlimAudioFileRefactor)

    def retranslateUi(self, SlimAudioFileRefactor):
        _translate = QtCore.QCoreApplication.translate
        SlimAudioFileRefactor.setWindowTitle(_translate("SlimAudioFileRefactor", "Slim Audio File Refactor"))
        self.label.setText(_translate("SlimAudioFileRefactor", "Select audio folder directory"))
        self.pushButton.setText(_translate("SlimAudioFileRefactor", "..."))
        self.label_2.setText(_translate("SlimAudioFileRefactor", "Select CSV folder directory"))
        self.pushButton_2.setText(_translate("SlimAudioFileRefactor", "..."))
        self.pushButton_3.setText(_translate("SlimAudioFileRefactor", "RENAME"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("SlimAudioFileRefactor", "Rename Audio "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SlimAudioFileRefactor", "Tab 2"))
